author: "Tobe O <thosakwe@gmail.com>"
description: "JS Interpreter in Dart."
homepage: "https://github.com/thosakwe/samurai.git"
name: "samurai"
version: "1.0.0-dev"
dependencies: 
  parsejs: "^1.1.0"
  prototype: "^1.0.0"
dev_dependencies: 
  test: "^0.12.17+3"
