author: "Tobe O <thosakwe@gmail.com>"
description: "JS Interpreter in Dart."
homepage: "https://github.com/thosakwe/samurai.git"
name: "samurai"
version: 0.0.0
dependencies:
  args: ^0.13.7
  name_from_symbol: ^1.0.0
  parsejs: "^1.1.0"
  prototype: "^1.0.0"
dev_dependencies: 
  build_runner: ^0.3.0
  check_for_update: ^1.0.0
  test: "^0.12.17+3"
executables:
  samurai: samurai
