name: samurai
description: JS Interpreter in Dart.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0 <=2.0.0"
homepage: https://github.com/thosakwe/samurai.git
version: 0.0.0
dependencies:
  parsejs: ^1.1.0
  symbol_table: ^1.0.0
dev_dependencies:
  test: ^0.12.0
